:experimental:
:commandkey: &#8984;
:toc: macro
:source-highlighter: highlight.js

= Add Apache SCIMple to your Spring Boot App

Today, I'll show you how to build a JHipster app that's uses OAuth and OIDC for authentication and Apache SCIMple to keep users in sync.

**Prerequisites**:

- https://sdkman.io/[Java] 17+
- https://nodejs.com/[Node.js] 16+

toc::[]

== Create a Spring Boot app with JHipster

. Install JHipster nightly:
+
[source,shell]
----
git clone -b spring-boot-3.0-m4 git@github.com:jhipster/jhipster-bom.git
cd jhipster-bom && ./mvnw install -Dgpg.skip=true && cd ..
git clone -b spring-boot-3.0-m4 https://github.com/jhipster/generator-jhipster.git
cd generator-jhipster && npm link
----

. Create a new directory for your project and `cd` into it:
+
[source,shell]
----
take spring-boot-scimple
----

. Create a new project:
+
[source,shell]
----
jhipster jdl 21-points.jh
----

. Run it and make sure end-to-end tests pass:
+
[source,shell]
----
./gradlew
# open a new terminal window
npm run e2e
----

. Add Apache SCIMple dependencies:
+
[source,groovy]
.build.gradle
----

implementation "org.apache.directory.scim:scim-server:${scimpleVersion}"
implementation "org.apache.directory.scim:scim-spring-boot-starter:${scimpleVersion}"
----
+
[source,groovy]
.settings.gradle
----
scimpleVersion=1.0.0-SNAPSHOT
----
+
If you're using Maven:
+
[source,xml]
----
<scimple.version>1.0.0-SNAPSHOT</scimple.version>
...
<dependency>
    <groupId>org.apache.directory.scim</groupId>
    <artifactId>scim-spring-boot-starter</artifactId>
    <version>${scimple.version}</version>
</dependency>
<dependency>
    <groupId>org.apache.directory.scim</groupId>
    <artifactId>scim-server</artifactId>
    <version>${scimple.version}</version>
</dependency>
----

. Create a `ScimUserService` class that implements `Repository<User>`: [`scim-user`]
+
[source,java]
----
// todo: paste final code
----

. Create a `ScimGroupService` class that implements `Repository<Group>`: [`scim-group`]
+
[source,java]
----
// todo: paste final code
----

. Turn down logging from Jersey and JAXB:
+
[source,xml]
.src/main/resources/logback-spring.xml
----
<logger name="org.glassfish" level="WARN"/>
----

. Configure Spring to serve up Jersey endpoint at `/scim`:
+
[source,yaml]
.src/main/resources/config/application.yml
----
jersey:
    application-path: /scim
----

. Update `SecurityConfiguration` to skip CSRF for Jersey endpoints:
+
[source,java]
.src/main/java/com/okta/developer/config/SecurityConfiguration.java
----
http
    .csrf()
    .ignoringAntMatchers("/h2-console/**", "/scim/**")
----

. Enable CORS for `/scim/**`:
+
[source,java]
.src/main/java/com/okta/developer/config/WebConfigurer.java
----
source.registerCorsConfiguration("/scim/**", config);
----

. Update `AccountResource#getAccount()` to get user from database:
+
[source,java]
----
@GetMapping("/account")
public AdminUserDTO getAccount() {
    Optional<String> email = SecurityUtils.getCurrentUserLogin();

    if (email.isPresent()) {
        Optional<User> user = userService.getUserWithAuthoritiesByLogin(email.get());
        if (user.isPresent()) {
            return new AdminUserDTO(user.get());
        }
    }

    throw new AccountResourceException("User could not be found");
}
----

. Start ngrok and copy the https URL:
+
[source,shell]
----
ngrok http 8080
----

== Configure Okta for SCIM

https://developer.okta.com/blog/2021/09/01/flask-scim-server#option-1-scim-template-app[Create a SCIM Template App] on Okta, or use the following steps:

. Log in to Okta and go to **Applications**.

. **Browse App Catalogue** and select `SCIM 2.0 Test App (Header Auth)`.

. In the **Sign-On Options tab**, select **Secure Web Authentication**.

. Tab over to **Provisioning** > **Configure API Integration** > **Enable API Integration**.

. Put the ngrok URL in the **Base URL** field and append `/scim` to the end.

. Click **Test API Credentials**. You can check the ngrok logs at http://localhost:4040.

. **Save** and select **Edit** next to **Provisioning to App**. Select the following:

- Create Users
- Update User Attributes
- Deactive Users

. **Save** these settings.

== Test syncing identities

. When a user is assigned to the Okta app, a `POST` will be sent to `/scim/Users`

. When a group is assigned, a `POST` will be sent to `/scim/Users` with each member

. If Push Groups enabled, assigning a new group will `POST` to `/scim/Groups`

. Update a user's attributes to send a `PUT` or `PATCH` to `/scim/Users/{id}`

. Remove a user to send a `PATCH` to  `/scim/Users/{id}` to deactivate the user

== Protect the SCIM endpoints with Spring Security

. Configure basic authentication or OAuth.
